# Generated by Django 4.2.1 on 2023-06-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genre",
            old_name="genre",
            new_name="name",
        ),
    ]
