# Generated by Django 4.2.1 on 2023-06-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_remove_genre_movies_genre_genre_valid_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="actor",
            table="actors",
        ),
        migrations.AlterModelTable(
            name="director",
            table="directors",
        ),
        migrations.AlterModelTable(
            name="genre",
            table="genre",
        ),
        migrations.AlterModelTable(
            name="movie",
            table="movies",
        ),
        migrations.AlterModelTable(
            name="playin",
            table="play_in",
        ),
    ]
