# Generated by Django 4.2.1 on 2023-06-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_actor_table_alter_director_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actor",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="movie",
            options={"managed": True},
        ),
    ]
